import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — WealthTrack',
  description: 'Terms of service and financial disclaimer for WealthTrack personal finance application.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-8 animate-fade-in text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
      <div className="space-y-2">
        <span className="text-xs font-bold uppercase tracking-wider text-sky-600 dark:text-sky-400">
          Legal Agreement
        </span>
        <h1 className="text-3xl sm:text-4xl font-black text-slate-900 dark:text-white tracking-tight">
          Terms of Service
        </h1>
        <p className="text-xs text-slate-400">Effective Date: September 2026 • WealthTrack</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-base font-black text-slate-900 dark:text-white">1. Informational & Educational Tool</h2>
        <p>
          WealthTrack is a personal finance tracking and mathematical computation software utility. WealthTrack does not
          provide personalized financial, tax, legal, or investment advice. Any calculations, health scores, metrics, or
          projections generated by the application are purely mathematical estimates based on user-entered variables.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-black text-slate-900 dark:text-white">2. No Guarantee of Investment Returns</h2>
        <p>
          Calculators (such as SIP, Lumpsum, CAGR, and PPF) model potential compounding outcomes based on hypothetical
          rates entered by the user. Real-world financial market returns fluctuate, and historical performance is not
          guarantee of future returns.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-black text-slate-900 dark:text-white">3. User Responsibility for Data Backups</h2>
        <p>
          Because WealthTrack prioritizes privacy by keeping data entirely within your browser&apos;s local IndexedDB
          environment, clearing your browser cache or switching devices without exporting a backup may result in loss of
          records. Users are strongly encouraged to routinely download a JSON backup from the Settings page.
        </p>
      </section>

      <div className="pt-8 border-t border-slate-100 dark:border-slate-800 text-xs text-slate-400">
        Founded by ANKIT KUMAR • WealthTrack Personal Finance Management
      </div>
    </div>
  );
}
